# Generated by Django 4.2.25 on 2025-10-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0003_contadorvisitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=7, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
