# Generated by Django 4.2.25 on 2025-10-15 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0004_tipodoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipodoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='app_ecommerce.tipodoc'),
        ),
    ]
